---
title: "Homework 6"
author: "Helle Leth Skjetne"
date: "10/5/2020"
output: github_document
---

##Homework Response:

***

#Good Plot: 
  Source: https://datasmart.ash.harvard.edu/news/article/best-practices-covid-19-data-visualizations

For the “good” plot, answer the following questions:
### 1.	Describe the plot. Be sure to describe the data set it came from, the type of plot (scatterplot, line, box-and-whiskers), and any other notable features.
This is a box and line plot that is intended to visualize case information related to COVID-19. The data is provided by Allegheny County, Pennsylvania and is intended to keep residents informed about the public health treat in their area. A notable feature with this plot is that the plot clearly differentiates between probable and confirmed COVID-19 cases, and that it also contains layered information (e.g., deaths/cases by date and total deaths/cases by date). The combination of the data visualization makes it easy for the viewer to read the data with additional guidance (e.g., text to explain the plots). 

### 2.	What is the plot trying to communicate?
The plot is trying to communicate the deaths and cases (confirmed and probable) related to COVID-19 across a period of time.  

### 3.	Why do you think this plot is successful?
The plot is successful because I am able to derive accurate information from the graph, and the data appears to be displayed in a transparent way. The fact that the plot presents both probable and confirmed deaths makes the data reliable 

### 4.	Can you think of anything that could make the plot more successful? If not, what is a common plotting error that this plot avoided?
One think that could be done to make this plot more successful is to make the division between the date intervals on the x-axis so that the binning used to display cases/deaths by date is more obvious. Also, it is unclear what the light grey part of the graph in the top right side is trying to display and this should have been labeled more clearly (e.g., called out or using a significantly different color as it can be hard to tell apart from the darker grey color used to display confirmed cases). 

***

#Bad Plot:
  Source: https://stats.stackexchange.com/questions/73817/overlapping-time-series-is-there-any-better-way-to-visualize-them

For the “bad” plot, answer the following questions:
###  1.	Describe the plot as you did with the “good” plot.
The graph is a line plot that is supposed to show trend lines for 7 stock prices from a time series dataset. A major issue with the plot is that there are no labels for the x- and y-axes, although the x-axis should be labeled as “Index” and it is unknown what the y-axis should communicate. 

### 2.	What is the plot trying to communicate?
The plot is supposed to show that that trend lines are layered (e.g., brown line on the top and red/orange at the bottom). However, the plot is way too busy to be able to tell this, as it is showing way too many lines at one. Also, there are way too many colors and they are not color blind friendly. At this point it is almost impossible to determine what the plot is trying to communicate. A good plot should communicate its message without the need of an explanation, and the way the plot is displayed right now it is impossible to obtain any information.

### 3.	In what way does the plot obscure the meaning of the data, or mislead the reader?
Due to the large amount of data and colors displayed in the graph it is almost impossible to tell the data apart. and no information can be derived from the plot.

### 4.	What could be done to make the plot easier to read, or more honest?
One way to make the data clearer would be to bin or integrate the time series. A cumulative price series would be a better way to visually display the differences that the viewer is supposed to observe by looking at the plot. It would be better if the data was binned into fewer bins, and also utilized fewer colors that were color blind accomodating, and also utilized different textures (e.g., dashed lines)

***
